name: Run Journey Tests on GitHub

on:
  workflow_dispatch:
    inputs:
      test-tags:
        description: Cucumber tag expression to run
        required: false
        default: '@smoke'
        type: string
  workflow_call:
    inputs:
      test-tags:
        description: Cucumber tag expression to run
        required: false
        default: '@smoke'
        type: string

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'
  PROTOTYPE_URL: ${{ secrets.PROTOTYPE_URL }}
  PROTOTYPE_PASSWORD: ${{ secrets.PROTOTYPE_PASSWORD }}
  DEV_DATAVERSE_BASE_URL: ${{ secrets.DEV_DATAVERSE_BASE_URL }}
  DEV_DATAVERSE_CLIENT_ID: ${{ secrets.DEV_DATAVERSE_CLIENT_ID }}
  TEST_DATAVERSE_BASE_URL: ${{ secrets.TEST_DATAVERSE_BASE_URL }}
  TEST_DATAVERSE_CLIENT_ID: ${{ secrets.TEST_DATAVERSE_CLIENT_ID }}
  API_TOKEN_VERSION: ${{ secrets.API_TOKEN_VERSION }}
  API_TOKEN_GRANT_TYPE: ${{ secrets.API_TOKEN_GRANT_TYPE }}
  API_TOKEN_RESOURCE: ${{ secrets.API_TOKEN_RESOURCE }}
  API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
  API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
  API_BEARER_TOKEN: ${{ secrets.API_BEARER_TOKEN }}
  SEARCH_PERMIT_API_PATH: ${{ secrets.SEARCH_PERMIT_API_PATH }}
  ENDORSE_PERMIT_API_PATH: ${{ secrets.ENDORSE_PERMIT_API_PATH }}
  RETRIEVE_PERMIT_API_PATH: ${{ secrets.RETRIEVE_PERMIT_API_PATH }}
  HEADLESS: 'true'

jobs:
  build:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: DEFRA/econtrol-acceptance-tests/run-journey-tests@feature/github-actions-setup
        with:
          test-tags: ${{ inputs.test-tags || '@smoke' }}
