name: Run Journey Tests on GitHub

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: '094954420758'
  PROTOTYPE_URL: ${{ secrets.PROTOTYPE_URL }}
  PROTOTYPE_PASSWORD: ${{ secrets.PROTOTYPE_PASSWORD }}
  HEADLESS: 'true'

jobs:
  build:
    name: Run Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: DEFRA/econtrol-acceptance-tests/run-journey-tests@feature/github-actions-setup